
import React from 'react';
import { useNavigate } from 'react-router-dom';
import MainLayout from '@/components/Layout/MainLayout';
import { useAuth } from '@/contexts/SecureAuthContext';
import { useCustomer } from '@/contexts/CustomerContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import CustomerNewHeader from '@/components/Customer/CustomerNewHeader';
import CustomerForm, { CustomerFormValues } from '@/components/Customer/CustomerForm';

const CustomerNew = () => {
  const { user } = useAuth();
  const { addCustomer } = useCustomer();
  const navigate = useNavigate();
  const { toast } = useToast();

  const handleSubmit = async (data: CustomerFormValues) => {
    if (!user) return;

    const newCustomer = {
      id: '', // Will be generated by database
      name: data.name,
      mobile: data.mobile,
      company: data.company,
      email: data.email,
      leadSource: data.leadSource,
      licenseType: data.licenseType,
      amount: parseFloat(data.amount),
      status: 'Draft' as const,
      user_id: user.id,
      documents: [],
      comments: [],
      statusHistory: []
    };
    
    try {
      await addCustomer(newCustomer);
      
      toast({
        title: "Success",
        description: "Customer application created successfully with Google Drive folder",
      });
      
      navigate('/customers');
    } catch (error) {
      console.error('Customer creation error:', error);
      
      if (error instanceof Error && error.message.includes('Google Drive')) {
        toast({
          title: "Partial Success",
          description: "Customer created but Google Drive folder creation failed. Documents can still be uploaded locally.",
          variant: "destructive",
        });
        // Still navigate to customers list even if Drive folder creation fails
        navigate('/customers');
      } else {
        toast({
          title: "Error",
          description: "Failed to create customer application. Please try again.",
          variant: "destructive",
        });
      }
    }
  };

  return (
    <MainLayout>
      <div className="space-y-6">
        <CustomerNewHeader 
          title="Add New Customer" 
          description="Create a new customer application with Google Drive integration" 
        />
        
        <Card>
          <CardHeader>
            <CardTitle>Customer Information</CardTitle>
          </CardHeader>
          <CardContent>
            <CustomerForm onSubmit={handleSubmit} />
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
};

export default CustomerNew;
