
import React, { useState, useEffect, useMemo, Suspense } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import DashboardStats from '@/components/Dashboard/DashboardStats';
import DashboardFilters from '@/components/Dashboard/DashboardFilters';
import EmptyDashboardState from '@/components/Dashboard/EmptyDashboardState';
import DashboardHeader from '@/components/Dashboard/DashboardHeader';
import { useOptimizedCustomerData } from '@/hooks/useOptimizedCustomerData';
import { useAuth } from '@/contexts/SecureAuthContext';
import { supabase } from '@/lib/supabase';
import { BarChart3, Users, Calendar, ChevronDown, X, RotateCcw, CheckCircle, Clock, DollarSign, Loader2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useIsMobile } from '@/hooks/use-mobile';
import { cn } from '@/lib/utils';
import { LazyLoadingBoundary } from '@/components/Performance/LazyLoadingBoundary';

// Lazy load heavy components
const ResponsiveCustomerTable = React.lazy(() => import('@/components/Customer/ResponsiveCustomerTable'));
const EnhancedCustomerTable = React.lazy(() => import('@/components/Customer/EnhancedCustomerTable'));
const UserAnalytics = React.lazy(() => import('@/components/Analytics/UserAnalytics'));

const OptimizedDashboard = () => {
  const { 
    customers, 
    dashboardStats, 
    refreshData, 
    isLoading,
    pagination,
    loadNextPage,
    loadPreviousPage,
    hasNextPage,
    hasPreviousPage
  } = useOptimizedCustomerData(50);
  const { user, isAdmin } = useAuth();
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  
  // Widget selection state - default to applications
  const [activeWidget, setActiveWidget] = useState<'applications' | 'completed' | 'pending' | 'revenue'>('applications');
  
  // Reset status filter when widget changes to avoid showing incorrect data
  const handleWidgetChange = (widget: 'applications' | 'completed' | 'pending' | 'revenue') => {
    setActiveWidget(widget);
    setStatusFilter('all'); // Reset status filter when widget changes
  };
  
  // Enhanced date filtering for admin revenue
  const currentDate = new Date();
  const [selectedMonths, setSelectedMonths] = useState<number[]>([currentDate.getMonth() + 1]); // 1-based months
  const [revenueYear, setRevenueYear] = useState(currentDate.getFullYear());
  const [isAutoRange, setIsAutoRange] = useState(false);
  
  // Generate months from start date to current date when auto range is enabled
  const autoGeneratedMonths = useMemo(() => {
    if (!isAutoRange) return [];
    
    // Get earliest customer created_at date
    const earliestCustomer = customers.reduce((earliest, customer) => {
      const customerDate = new Date(customer.created_at || '');
      const earliestDate = new Date(earliest.created_at || '');
      return customerDate < earliestDate ? customer : earliest;
    }, customers[0]);
    
    if (!earliestCustomer?.created_at) return [];
    
    const startDate = new Date(earliestCustomer.created_at);
    const endDate = new Date();
    const months: number[] = [];
    
    let current = new Date(startDate.getFullYear(), startDate.getMonth(), 1);
    while (current <= endDate) {
      if (current.getFullYear() === revenueYear) {
        months.push(current.getMonth() + 1);
      }
      current.setMonth(current.getMonth() + 1);
    }
    
    return months;
  }, [customers, revenueYear, isAutoRange]);
  
  // Update selected months when auto range changes
  useEffect(() => {
    if (isAutoRange && autoGeneratedMonths.length > 0) {
      setSelectedMonths(autoGeneratedMonths);
    }
  }, [isAutoRange, autoGeneratedMonths]);

  // Optimized real-time subscription - only listen to customer changes
  useEffect(() => {
    const channel = supabase
      .channel('dashboard-changes')
      .on('postgres_changes', 
        { event: '*', schema: 'public', table: 'customers' },
        () => {
          console.log('Customer data changed, refreshing...');
          refreshData();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [refreshData]);

  // Optimized filtering - using smaller dataset
  const filteredCustomers = useMemo(() => {
    // Since pagination already handles role-based access, just apply widget and search filters
    let statusFilteredCustomers = customers;
    
    if (activeWidget === 'completed') {
      const currentDate = new Date();
      const currentMonth = currentDate.getMonth() + 1;
      const currentYear = currentDate.getFullYear();
      
      statusFilteredCustomers = customers.filter(c => {
        const isCompletedOrPaid = c.status === 'Complete' || c.status === 'Paid';
        if (!isCompletedOrPaid) return false;
        
        const customerDate = new Date(c.updated_at || c.created_at || '');
        const customerMonth = customerDate.getMonth() + 1;
        const customerYear = customerDate.getFullYear();
        
        return customerMonth === currentMonth && customerYear === currentYear;
      });
    } else if (activeWidget === 'pending') {
      statusFilteredCustomers = customers.filter(c => 
        !['Complete', 'Paid', 'Rejected', 'Draft'].includes(c.status)
      );
    } else if (activeWidget === 'revenue') {
      statusFilteredCustomers = customers.filter(c => {
        const isRevenueGenerating = c.status === 'Complete' || c.status === 'Paid';
        if (!isRevenueGenerating) return false;
        
        if (isAdmin && selectedMonths.length > 0) {
          const customerDate = new Date(c.updated_at || c.created_at || '');
          const customerMonth = customerDate.getMonth() + 1;
          const customerYear = customerDate.getFullYear();
          
          return selectedMonths.includes(customerMonth) && customerYear === revenueYear;
        }
        
        return true;
      });
    } else {
      statusFilteredCustomers = customers.filter(c => c.status === 'Draft');
    }
    
    return statusFilteredCustomers.filter(customer => {
      const matchesSearch = customer.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           customer.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           customer.company.toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesStatus = statusFilter === 'all' || customer.status === statusFilter;
      
      return matchesSearch && matchesStatus;
    });
  }, [customers, searchTerm, statusFilter, isAdmin, activeWidget, selectedMonths, revenueYear]);

  // Use pre-calculated dashboard stats for better performance
  const stats = dashboardStats;

  // Helper functions for month selection
  const toggleMonth = (month: number) => {
    if (isAutoRange) return; // Don't allow manual selection in auto range mode
    
    setSelectedMonths(prev => 
      prev.includes(month)
        ? prev.filter(m => m !== month)
        : [...prev, month].sort((a, b) => a - b)
    );
  };

  const selectAllMonths = () => {
    if (isAutoRange) return;
    setSelectedMonths(Array.from({ length: 12 }, (_, i) => i + 1));
  };

  const clearAllMonths = () => {
    if (isAutoRange) return;
    setSelectedMonths([]);
  };

  const resetToCurrentMonth = () => {
    setIsAutoRange(false);
    setSelectedMonths([currentDate.getMonth() + 1]);
    setRevenueYear(currentDate.getFullYear());
  };

  const getMonthName = (month: number) => {
    return new Date(2000, month - 1).toLocaleString('default', { month: 'long' });
  };

  // Get dynamic content based on active widget
  const getWidgetContent = () => {
    switch (activeWidget) {
      case 'applications':
        return {
          title: isAdmin ? 'All Applications' : 'My Applications',
          description: `Showing ${filteredCustomers.length} ${isAdmin ? 'total applications' : 'applications'} of all statuses`,
          icon: Users
        };
      case 'completed':
        return {
          title: 'Completed Applications',
          description: `Showing ${filteredCustomers.length} completed/paid applications from current month`,
          icon: CheckCircle
        };
      case 'pending':
        return {
          title: 'Submitted Applications',
          description: `Showing ${filteredCustomers.length} submitted applications in progress`,
          icon: Clock
        };
      case 'revenue':
        const revenueDesc = isAdmin && selectedMonths.length > 0 
          ? `Showing ${filteredCustomers.length} revenue applications from ${selectedMonths.length} selected month(s) of ${revenueYear}` 
          : `Showing ${filteredCustomers.length} revenue-generating applications with advanced filtering available`;
        return {
          title: isAdmin ? 'Total Revenue (Advanced)' : 'My Revenue',
          description: revenueDesc,
          icon: DollarSign
        };
      default:
        return {
          title: 'Applications',
          description: 'Select a widget to view details',
          icon: Users
        };
    }
  };

  const widgetContent = getWidgetContent();

  const handleDataRefresh = () => {
    refreshData();
  };

  const handleCreateCustomer = () => {
    navigate('/customers/new');
  };

  // Simplified loading state
  const LoadingSpinner = () => (
    <div className="flex items-center justify-center p-8">
      <Loader2 className="h-8 w-8 animate-spin text-primary" />
      <span className="ml-2 text-sm text-muted-foreground">Loading...</span>
    </div>
  );

  return (
    <div className={cn(
      "space-y-4 xs:space-y-5 sm:space-y-6 lg:space-y-8",
      "pb-4 xs:pb-6 sm:pb-8",
      "max-w-full overflow-hidden"
    )}>
        {/* Enhanced Header */}
        <DashboardHeader
          userName={user?.profile?.name}
          userEmail={user?.email}
          onCreateCustomer={handleCreateCustomer}
        />

        {/* Conditional Filters - Only show revenue filter when revenue widget is active */}
        {isAdmin && activeWidget === 'revenue' && (
          <Card className="shadow-sm border-0 bg-gradient-to-br from-card to-card/50">
            <CardHeader className="pb-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-primary/10">
                    <Calendar className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <CardTitle className="text-lg">Revenue Filter</CardTitle>
                    <p className="text-sm text-muted-foreground">
                      Filter total revenue by selecting multiple months or auto-populate from start date
                    </p>
                  </div>
                </div>
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={resetToCurrentMonth}
                  className="flex items-center gap-2"
                >
                  <RotateCcw className="h-4 w-4" />
                  Reset
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium">Year:</label>
                    <Select value={revenueYear.toString()} onValueChange={(value) => setRevenueYear(parseInt(value))}>
                      <SelectTrigger className="w-[100px]">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-background border shadow-lg z-50">
                        {Array.from({ length: 10 }, (_, i) => {
                          const year = currentDate.getFullYear() - 5 + i;
                          return (
                            <SelectItem key={year} value={year.toString()}>
                              {year}
                            </SelectItem>
                          );
                        })}
                      </SelectContent>
                    </Select>
                  </div>
                  
                  <div className="flex items-center space-x-2">
                    <Checkbox 
                      id="auto-range" 
                      checked={isAutoRange}
                      onCheckedChange={(checked) => setIsAutoRange(checked as boolean)}
                    />
                    <label htmlFor="auto-range" className="text-sm font-medium cursor-pointer">
                      Auto-populate from start date to current
                    </label>
                  </div>
                </div>
              </div>
              
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-sm font-medium">
                    Selected Months ({selectedMonths.length}/12):
                  </label>
                  {!isAutoRange && (
                    <div className="flex items-center gap-2">
                      <Button variant="outline" size="sm" onClick={selectAllMonths}>
                        Select All
                      </Button>
                      <Button variant="outline" size="sm" onClick={clearAllMonths}>
                        Clear All
                      </Button>
                    </div>
                  )}
                </div>
                
                {/* Month Selection */}
                <div className="space-y-2">
                  {selectedMonths.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {selectedMonths.map(month => (
                        <Badge 
                          key={month} 
                          variant="secondary" 
                          className="flex items-center gap-1 px-3 py-1"
                        >
                          {getMonthName(month)}
                          {!isAutoRange && (
                            <button
                              onClick={() => toggleMonth(month)}
                              className="ml-1 hover:bg-destructive/20 rounded-full p-0.5"
                            >
                              <X className="h-3 w-3" />
                            </button>
                          )}
                        </Badge>
                      ))}
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">No months selected</p>
                  )}
                  
                  {!isAutoRange && (
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button variant="outline" className="w-full justify-start">
                          <ChevronDown className="h-4 w-4 mr-2" />
                          Add Months
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-80 p-4 bg-background border shadow-lg z-50">
                        <div className="grid grid-cols-3 gap-2">
                          {Array.from({ length: 12 }, (_, i) => {
                            const month = i + 1;
                            const isSelected = selectedMonths.includes(month);
                            return (
                              <Button
                                key={month}
                                variant={isSelected ? "default" : "outline"}
                                size="sm"
                                onClick={() => toggleMonth(month)}
                                className="justify-start"
                              >
                                {getMonthName(month)}
                              </Button>
                            );
                          })}
                        </div>
                      </PopoverContent>
                    </Popover>
                  )}
                  
                  {isAutoRange && autoGeneratedMonths.length > 0 && (
                    <p className="text-xs text-muted-foreground">
                      Auto-populated {autoGeneratedMonths.length} months from earliest customer ({customers.length > 0 ? new Date(customers.reduce((earliest, customer) => {
                        const customerDate = new Date(customer.created_at || '');
                        const earliestDate = new Date(earliest.created_at || '');
                        return customerDate < earliestDate ? customer : earliest;
                      }, customers[0]).created_at || '').toLocaleDateString() : 'N/A'}) to current date
                    </p>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Admin Dashboard with Tabs */}
        {isAdmin ? (
          <Tabs defaultValue="customers" className="space-y-8">
            <TabsList className="grid w-full grid-cols-2 max-w-md h-12 bg-muted/50">
              <TabsTrigger value="customers" className="flex items-center gap-2 h-10 data-[state=active]:bg-background data-[state=active]:shadow-sm">
                <Users className="h-4 w-4" />
                <span className="font-medium">Customers</span>
              </TabsTrigger>
              <TabsTrigger value="analytics" className="flex items-center gap-2 h-10 data-[state=active]:bg-background data-[state=active]:shadow-sm">
                <BarChart3 className="h-4 w-4" />
                <span className="font-medium">Analytics</span>
              </TabsTrigger>
            </TabsList>

            <TabsContent value="customers" className="space-y-6">
              {/* Statistics Cards inside Customers tab */}
              <DashboardStats 
                stats={stats} 
                selectedMonths={selectedMonths} 
                revenueYear={revenueYear}
                onWidgetClick={handleWidgetChange}
                activeWidget={activeWidget}
              />

              {customers.length === 0 ? (
                <EmptyDashboardState onCreateCustomer={handleCreateCustomer} />
              ) : (
                <div className="space-y-6">
                  <DashboardFilters
                    searchTerm={searchTerm}
                    setSearchTerm={setSearchTerm}
                    statusFilter={statusFilter}
                    setStatusFilter={setStatusFilter}
                    onRefresh={handleDataRefresh}
                    isLoading={isLoading}
                    activeWidget={activeWidget}
                  />
                  
                  <Card className="shadow-sm border-0 bg-gradient-to-br from-card to-card/50">
                    <CardHeader className="pb-4 border-b border-border/50">
                      <CardTitle className="flex items-center gap-3">
                        <div className="p-2 rounded-lg bg-primary/10">
                          <widgetContent.icon className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <span className="text-xl font-semibold">{widgetContent.title}</span>
                          <p className="text-sm text-muted-foreground font-normal mt-1">
                            {widgetContent.description}
                          </p>
                        </div>
                      </CardTitle>
                    </CardHeader>
                     <CardContent className="p-0">
                       <LazyLoadingBoundary>
                         <EnhancedCustomerTable 
                           customers={filteredCustomers} 
                           onDataChange={handleDataRefresh}
                         />
                       </LazyLoadingBoundary>
                     </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>

             <TabsContent value="analytics" className="space-y-6">
               <LazyLoadingBoundary>
                 <UserAnalytics />
               </LazyLoadingBoundary>
             </TabsContent>
          </Tabs>
        ) : (
          /* Regular User Dashboard with Tabs */
          <Tabs defaultValue="customers" className="space-y-8">
            <TabsList className="grid w-full grid-cols-1 max-w-md h-12 bg-muted/50">
              <TabsTrigger value="customers" className="flex items-center gap-2 h-10 data-[state=active]:bg-background data-[state=active]:shadow-sm">
                <Users className="h-4 w-4" />
                <span className="font-medium">Customers</span>
              </TabsTrigger>
            </TabsList>

            <TabsContent value="customers" className="space-y-6">
              {/* Statistics Cards inside Customers tab */}
              <DashboardStats 
                stats={stats} 
                onWidgetClick={handleWidgetChange}
                activeWidget={activeWidget}
              />

              {customers.length === 0 ? (
                <EmptyDashboardState onCreateCustomer={handleCreateCustomer} />
              ) : (
                <div className="space-y-6">
                  <DashboardFilters
                    searchTerm={searchTerm}
                    setSearchTerm={setSearchTerm}
                    statusFilter={statusFilter}
                    setStatusFilter={setStatusFilter}
                    onRefresh={handleDataRefresh}
                    isLoading={isLoading}
                    activeWidget={activeWidget}
                  />
                  
                  <Card className="shadow-sm border-0 bg-gradient-to-br from-card to-card/50">
                    <CardHeader className="pb-4 border-b border-border/50">
                      <CardTitle className="flex items-center gap-3">
                        <div className="p-2 rounded-lg bg-primary/10">
                          <widgetContent.icon className="h-5 w-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <span className="text-xl font-semibold">{widgetContent.title}</span>
                          <p className="text-sm text-muted-foreground font-normal mt-1">
                            {widgetContent.description}
                          </p>
                        </div>
                      </CardTitle>
                    </CardHeader>
                     <CardContent className="p-0">
                       <LazyLoadingBoundary>
                         <EnhancedCustomerTable 
                           customers={filteredCustomers} 
                           onDataChange={handleDataRefresh}
                         />
                       </LazyLoadingBoundary>
                     </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>
          </Tabs>
        )}
      </div>
    );
  };

export default OptimizedDashboard;
