-- Seed comprehensive decision engine rules into the active webflow configuration
UPDATE webflow_configurations 
SET config_data = jsonb_set(
  config_data,
  '{rules}',
  '[
    {"id": "rule-eligibility-blocked-country", "rule_name": "Block High-Risk Countries", "rule_type": "eligibility", "description": "Reject applications from blocked countries", "priority": 1, "is_active": true, "conditions": [{"id": "cond-1", "field": "country.is_blocked", "operator": "equals", "value": true}], "actions": [{"id": "act-1", "type": "block", "message": "Applications from this country are not currently accepted"}]},
    {"id": "rule-eligibility-restricted-activity", "rule_name": "Block Restricted Activities", "rule_type": "eligibility", "description": "Reject applications with restricted business activities", "priority": 2, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.is_restricted", "operator": "equals", "value": true}], "actions": [{"id": "act-1", "type": "block", "message": "This business activity is not permitted"}]},
    {"id": "rule-edd-high-risk-country", "rule_name": "EDD for High-Risk Countries", "rule_type": "document", "description": "Require enhanced due diligence for high-risk nationalities", "priority": 3, "is_active": true, "conditions": [{"id": "cond-1", "field": "country.risk_level", "operator": "equals", "value": "high"}], "actions": [{"id": "act-1", "type": "require_document", "target": "source_of_funds_declaration"}, {"id": "act-2", "type": "require_document", "target": "bank_reference_letter"}, {"id": "act-3", "type": "show_warning", "message": "Enhanced Due Diligence required for this nationality"}]},
    {"id": "rule-edd-high-risk-activity", "rule_name": "EDD for High-Risk Activities", "rule_type": "document", "description": "Require additional documents for high-risk business activities", "priority": 4, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.risk_level", "operator": "equals", "value": "high"}], "actions": [{"id": "act-1", "type": "require_document", "target": "detailed_business_plan"}, {"id": "act-2", "type": "require_document", "target": "aml_compliance_certificate"}, {"id": "act-3", "type": "show_warning", "message": "This activity requires enhanced compliance review"}]},
    {"id": "rule-pricing-high-risk-activity", "rule_name": "High-Risk Activity Premium", "rule_type": "pricing", "description": "Apply 25% price increase for high-risk activities", "priority": 5, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.risk_level", "operator": "equals", "value": "high"}], "actions": [{"id": "act-1", "type": "set_price", "value": 1.25, "message": "25% premium applied for high-risk activity"}]},
    {"id": "rule-pricing-mainland-premium", "rule_name": "Mainland Setup Premium", "rule_type": "pricing", "description": "Apply additional fee for mainland jurisdictions", "priority": 6, "is_active": true, "conditions": [{"id": "cond-1", "field": "jurisdiction.type", "operator": "equals", "value": "mainland"}], "actions": [{"id": "act-1", "type": "set_price", "value": 5000, "message": "AED 5,000 additional for mainland setup"}]},
    {"id": "rule-cascade-freezone-docs", "rule_name": "Freezone Document Requirements", "rule_type": "document", "description": "Require specific documents for freezone applications", "priority": 7, "is_active": true, "conditions": [{"id": "cond-1", "field": "jurisdiction.type", "operator": "equals", "value": "freezone"}], "actions": [{"id": "act-1", "type": "require_document", "target": "passport_copy"}, {"id": "act-2", "type": "require_document", "target": "proof_of_address"}, {"id": "act-3", "type": "require_document", "target": "bank_statement"}]},
    {"id": "rule-cascade-mainland-docs", "rule_name": "Mainland Document Requirements", "rule_type": "document", "description": "Require additional documents for mainland applications", "priority": 8, "is_active": true, "conditions": [{"id": "cond-1", "field": "jurisdiction.type", "operator": "equals", "value": "mainland"}], "actions": [{"id": "act-1", "type": "require_document", "target": "passport_copy"}, {"id": "act-2", "type": "require_document", "target": "proof_of_address"}, {"id": "act-3", "type": "require_document", "target": "noc_from_sponsor"}, {"id": "act-4", "type": "require_document", "target": "local_service_agent_agreement"}]},
    {"id": "rule-workflow-approval-required", "rule_name": "Manual Approval Required", "rule_type": "workflow", "description": "Flag applications requiring manual approval", "priority": 9, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.requires_approval", "operator": "equals", "value": true}], "actions": [{"id": "act-1", "type": "set_field", "target": "requires_manual_review", "value": true}, {"id": "act-2", "type": "show_warning", "message": "This application requires manual approval from licensing authority"}]},
    {"id": "rule-eligibility-jurisdiction-activity-mismatch", "rule_name": "Jurisdiction-Activity Restriction", "rule_type": "eligibility", "description": "Block if activity not allowed in selected jurisdiction", "priority": 10, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.allowed_jurisdictions", "operator": "not_in", "value": "jurisdiction.code"}], "actions": [{"id": "act-1", "type": "block", "message": "This activity is not permitted in the selected jurisdiction"}]},
    {"id": "rule-edd-crypto-trading", "rule_name": "Crypto Trading EDD", "rule_type": "document", "description": "Enhanced requirements for cryptocurrency activities", "priority": 11, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.activity_code", "operator": "contains", "value": "crypto"}], "actions": [{"id": "act-1", "type": "require_document", "target": "aml_policy"}, {"id": "act-2", "type": "require_document", "target": "compliance_officer_cv"}, {"id": "act-3", "type": "require_document", "target": "source_of_funds_declaration"}, {"id": "act-4", "type": "show_warning", "message": "Virtual Asset Service Provider license may be required"}]},
    {"id": "rule-edd-money-exchange", "rule_name": "Money Exchange EDD", "rule_type": "document", "description": "Enhanced requirements for money exchange activities", "priority": 12, "is_active": true, "conditions": [{"id": "cond-1", "field": "activity.activity_code", "operator": "contains", "value": "exchange"}], "actions": [{"id": "act-1", "type": "require_document", "target": "central_bank_approval"}, {"id": "act-2", "type": "require_document", "target": "aml_policy"}, {"id": "act-3", "type": "show_warning", "message": "Central Bank of UAE approval required"}]},
    {"id": "rule-pricing-offshore-discount", "rule_name": "Offshore Setup Discount", "rule_type": "pricing", "description": "Apply discount for offshore company formation", "priority": 13, "is_active": true, "conditions": [{"id": "cond-1", "field": "jurisdiction.type", "operator": "equals", "value": "offshore"}], "actions": [{"id": "act-1", "type": "set_price", "value": 0.85, "message": "15% discount for offshore setup"}]},
    {"id": "rule-workflow-fast-track", "rule_name": "Fast Track Processing", "rule_type": "workflow", "description": "Enable fast track for low-risk applications", "priority": 14, "is_active": true, "conditions": [{"id": "cond-1", "field": "country.risk_level", "operator": "equals", "value": "low", "logic": "AND"}, {"id": "cond-2", "field": "activity.risk_level", "operator": "equals", "value": "low"}], "actions": [{"id": "act-1", "type": "set_field", "target": "processing_type", "value": "fast_track"}, {"id": "act-2", "type": "show_warning", "message": "Eligible for fast-track processing (3-5 business days)"}]},
    {"id": "rule-cascade-uae-national", "rule_name": "UAE National Benefits", "rule_type": "document", "description": "Reduced documentation for UAE nationals", "priority": 15, "is_active": true, "conditions": [{"id": "cond-1", "field": "country.code", "operator": "equals", "value": "AE"}], "actions": [{"id": "act-1", "type": "require_document", "target": "emirates_id"}, {"id": "act-2", "type": "show_warning", "message": "Simplified process for UAE nationals"}]}
  ]'::jsonb
),
updated_at = now()
WHERE is_active = true;